### PR TITLE
Fetch Quest and Win Game State

### PR DESCRIPTION
**Pull request by minamiren**
- can follow initial fetch quest line with NPC
- can win the game by going to spot that NPC sends you

### CODE REVIEW

**Comment by jinyLi-github** [comment]
tested both the web build one  and the GitHub branch one on local PC, have some difference Xx. 

On the web build, i can go to the final talk with NPC (though grab little food twice or though grab large amount of food at one), which he gives me the specific items (just I still haven't found in the scene yet, attached some screenshot here);
Scene on Lake01-WebBuild
Scene on Lake02-WebBuild


On the local PC, can't go to the final talk, the NPC seems always request more food and change all of them to the stick (attach another pic). 
Scene on Local PC-NPCRepeatOnHere

**Comment by minamiren** [comment]
Fixed above comment! I believe I have, at least.

**Comment by jinyLi-github** [comment]
- The NPC story (include the story end scene）is working!!

- Just the GameOver! scene (which shows when the health or food go to "0", then game over. ) looks not work? 

  

> 1. **If health to "0", cause the game over scene**, when clicking the buttons "start over?" or "quit",  it will jump back to the game world scene with the health in "0" status again immediatley or sometimes after the StartScene.
>   
>   https://github.com/user-attachments/assets/09cce597-4b07-47c9-8d88-64ea96c18d89
>   
>   
>   2. **If food to "0", cause the game over scene**, when  clicking the buttons "start over?" or "quit", it seems alwyas stays on the game over scene.
>   
>   https://github.com/user-attachments/assets/2c2daaeb-2a2e-4eb9-be88-5b55f78cabf4
>   
>

**Review by jinyLi-github — APPROVED** [review]
NPC dailogue with the story ending has nicelly done.

**Pull request merged**
